# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='recipient_id',
            field=models.CharField(max_length=1000),
        ),
    ]
