# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20171129_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswerpair',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='structuredanswer',
            name='entity',
            field=models.CharField(choices=[(b'duration', [(b'notice_period', b'notice_period'), (b'work_experience', b'work_experience'), (b'notice_period_none', b'notice_period_none')]), (b'ctc_inr', [(b'current_ctc_inr', b'current_ctc_inr'), (b'expect_ctc_inr', b'expect_ctc_inr')]), (b'location', b'Location'), (b'datetime', b'DateTime'), (b'boolean', b'Boolean'), (b'rating', b'Rating')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='structuredanswer',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='structuredanswer',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
